/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure Color where
  h : Int
  s : Int
  l : Int
deriving Repr, Inhabited, DecidableEq

inductive Mood where
  | Vibrant : Mood
  | SoftMuted : Mood
  | Pastel : Mood
  | DeepJewel : Mood
  | Earth : Mood
  | Neon : Mood
  | Custom : Mood
deriving Repr, Inhabited, DecidableEq

inductive Harmony where
  | Custom : Harmony
  | Complementary : Harmony
  | Triadic : Harmony
  | Analogous : Harmony
  | SplitComplement : Harmony
  | Square : Harmony
deriving Repr, Inhabited, DecidableEq

structure ContrastPair where
  fg : Int
  bg : Int
deriving Repr, Inhabited, DecidableEq

structure MoodBoundsResult where
  minS : Int
  maxS : Int
  minL : Int
  maxL : Int
deriving Repr, Inhabited, DecidableEq

structure SLPair where
  s : Int
  l : Int
deriving Repr, Inhabited, DecidableEq

structure Model where
  baseHue : Int
  mood : Mood
  harmony : Harmony
  colors : Array Color
  contrastPair : ContrastPair
  adjustmentH : Int
  adjustmentS : Int
  adjustmentL : Int
deriving Repr, Inhabited, DecidableEq

inductive Action where
  | GeneratePalette (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Action
  | AdjustColor (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Action
  | AdjustPalette (deltaH : Int) (deltaS : Int) (deltaL : Int) : Action
  | SelectContrastPair (fg : Int) (bg : Int) : Action
  | SetColorDirect (index : Int) (color : Color) : Action
  | RegenerateMood (mood : Mood) (randomSeeds : Array Int) : Action
  | RegenerateHarmony (harmony : Harmony) (randomSeeds : Array Int) : Action
  | RandomizeBaseHue (newBaseHue : Int) (randomSeeds : Array Int) : Action
deriving Repr, Inhabited

namespace Pure

def clamp (x : Int) (min : Int) (max : Int) : Int :=
  if x < min then
    min
  else
    if x > max then
      max
    else
      x

def normalizeHue (h : Int) : Int :=
  let normalized := h % 360
  if normalized < 0 then
    normalized + 360
  else
    normalized

def clampColor (c : Color) : Color :=
  { h := normalizeHue c.h, s := clamp c.s 0 100, l := clamp c.l 0 100 }

def moodBoundsOf (mood : Mood) : MoodBoundsResult :=
  match mood with
  | .Vibrant =>
    { minS := 70, maxS := 100, minL := 40, maxL := 60 }
  | .SoftMuted =>
    { minS := 20, maxS := 45, minL := 55, maxL := 75 }
  | .Pastel =>
    { minS := 0, maxS := 35, minL := 75, maxL := 100 }
  | .DeepJewel =>
    { minS := 60, maxS := 100, minL := 25, maxL := 45 }
  | .Earth =>
    { minS := 15, maxS := 40, minL := 30, maxL := 60 }
  | .Neon =>
    { minS := 90, maxS := 100, minL := 50, maxL := 65 }
  | .Custom =>
    { minS := 0, maxS := 100, minL := 0, maxL := 100 }

def colorSatisfiesMood (c : Color) (mood : Mood) : Bool :=
  match mood with
  | .Vibrant =>
    c.s ≥ 70 ∧ 40 ≤ c.l ∧ c.l ≤ 60
  | .SoftMuted =>
    20 ≤ c.s ∧ c.s ≤ 45 ∧ 55 ≤ c.l ∧ c.l ≤ 75
  | .Pastel =>
    c.s ≤ 35 ∧ c.l ≥ 75
  | .DeepJewel =>
    c.s ≥ 60 ∧ 25 ≤ c.l ∧ c.l ≤ 45
  | .Earth =>
    15 ≤ c.s ∧ c.s ≤ 40 ∧ 30 ≤ c.l ∧ c.l ≤ 60
  | .Neon =>
    c.s ≥ 90 ∧ 50 ≤ c.l ∧ c.l ≤ 65
  | .Custom =>
    true

def randomInRange (seed : Int) (min : Int) (max : Int) : Int :=
  if min = max then
    min
  else
    min + seed * (max - min) / 100

def goldenSLForMood (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) : SLPair :=
  let bounds := moodBoundsOf mood
  let spreadS := (seedS + colorIndex * 62) % 101
  let spreadL := (seedL + colorIndex * 38) % 101
  { s := randomInRange spreadS bounds.minS bounds.maxS, l := randomInRange spreadL bounds.minL bounds.maxL }

def generateColorGolden (h : Int) (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) : Color :=
  let sl := goldenSLForMood mood colorIndex seedS seedL
  { h := h, s := sl.s, l := sl.l }

def allColorsSatisfyMood (colors : Array Color) (mood : Mood) : Bool :=
  colorSatisfiesMood colors[0]! mood ∧ colorSatisfiesMood colors[1]! mood ∧ colorSatisfiesMood colors[2]! mood ∧ colorSatisfiesMood colors[3]! mood ∧ colorSatisfiesMood colors[4]! mood

def baseHarmonyHues (baseHue : Int) (harmony : Harmony) : Array Int :=
  match harmony with
  | .Complementary =>
    #[baseHue, normalizeHue (baseHue + 180)]
  | .Triadic =>
    #[baseHue, normalizeHue (baseHue + 120), normalizeHue (baseHue + 240)]
  | .Analogous =>
    #[normalizeHue (baseHue - 30), normalizeHue (baseHue - 15), baseHue, normalizeHue (baseHue + 15), normalizeHue (baseHue + 30)]
  | .SplitComplement =>
    #[baseHue, normalizeHue (baseHue + 150), normalizeHue (baseHue + 210)]
  | .Square =>
    #[baseHue, normalizeHue (baseHue + 90), normalizeHue (baseHue + 180), normalizeHue (baseHue + 270)]
  | .Custom =>
    #[]

def allHarmonyHues (baseHue : Int) (harmony : Harmony) : Array Int :=
  match harmony with
  | .Analogous =>
    #[normalizeHue (baseHue - 30), normalizeHue (baseHue - 15), baseHue, normalizeHue (baseHue + 15), normalizeHue (baseHue + 30)]
  | .Square =>
    #[baseHue, normalizeHue (baseHue + 90), normalizeHue (baseHue + 180), normalizeHue (baseHue + 270), normalizeHue (baseHue + 45)]
  | .Triadic =>
    #[baseHue, normalizeHue (baseHue + 120), normalizeHue (baseHue + 240), normalizeHue (baseHue + 35), normalizeHue (baseHue + 120 - 35)]
  | .SplitComplement =>
    #[baseHue, normalizeHue (baseHue + 150), normalizeHue (baseHue + 210), normalizeHue (baseHue + 35), normalizeHue (baseHue + 150 - 35)]
  | .Complementary =>
    #[baseHue, normalizeHue (baseHue + 180), normalizeHue (baseHue + 35), normalizeHue (baseHue + 180 + 35), normalizeHue (baseHue - 35)]
  | .Custom =>
    #[]

def huesMatchHarmony (colors : Array Color) (baseHue : Int) (harmony : Harmony) : Bool :=
  harmony = .Custom ∨ let expectedHues := allHarmonyHues baseHue harmony
if colors.size ≠ 5 ∨ expectedHues.size ≠ 5 then false else (colors[0]!).h = expectedHues[0]! ∧ (colors[1]!).h = expectedHues[1]! ∧ (colors[2]!).h = expectedHues[2]! ∧ (colors[3]!).h = expectedHues[3]! ∧ (colors[4]!).h = expectedHues[4]!

def generatePaletteColors (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Array Color :=
  let hues := allHarmonyHues baseHue harmony
  if hues.size ≠ 5 then
    #[generateColorGolden baseHue mood 0 randomSeeds[0]! randomSeeds[1]!, generateColorGolden baseHue mood 1 randomSeeds[2]! randomSeeds[3]!, generateColorGolden baseHue mood 2 randomSeeds[4]! randomSeeds[5]!, generateColorGolden baseHue mood 3 randomSeeds[6]! randomSeeds[7]!, generateColorGolden baseHue mood 4 randomSeeds[8]! randomSeeds[9]!]
  else
    #[generateColorGolden hues[0]! mood 0 randomSeeds[0]! randomSeeds[1]!, generateColorGolden hues[1]! mood 1 randomSeeds[2]! randomSeeds[3]!, generateColorGolden hues[2]! mood 2 randomSeeds[4]! randomSeeds[5]!, generateColorGolden hues[3]! mood 3 randomSeeds[6]! randomSeeds[7]!, generateColorGolden hues[4]! mood 4 randomSeeds[8]! randomSeeds[9]!]

def adjustColorSL (c : Color) (newHue : Int) (deltaS : Int) (deltaL : Int) : Color :=
  { h := newHue, s := clamp (c.s + deltaS) 0 100, l := clamp (c.l + deltaL) 0 100 }

def applyIndependentAdjustment (m : Model) (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let oldColor := m.colors[index.toNat]!
  let newColor := clampColor { h := oldColor.h + deltaH, s := oldColor.s + deltaS, l := oldColor.l + deltaL }
  let expectedHues := allHarmonyHues m.baseHue m.harmony
  let hueChanged := expectedHues.size = 5 ∧ newColor.h ≠ expectedHues[index.toNat]!
  let harmonyBroken := m.harmony ≠ .Custom ∧ hueChanged
  let moodBroken := m.mood ≠ .Custom ∧ ¬(colorSatisfiesMood newColor m.mood)
  let newColors := m.colors.set! index.toNat newColor
  let newHarmony := if harmonyBroken then .Custom else m.harmony
  let newMood := if moodBroken then .Custom else m.mood
  { m with colors := newColors, harmony := newHarmony, mood := newMood }

def applyLinkedAdjustment (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let newBaseHue := normalizeHue (m.baseHue + deltaH)
  let newHues := allHarmonyHues newBaseHue m.harmony
  let adjustedColors := if newHues.size = 5 then #[adjustColorSL m.colors[0]! newHues[0]! deltaS deltaL, adjustColorSL m.colors[1]! newHues[1]! deltaS deltaL, adjustColorSL m.colors[2]! newHues[2]! deltaS deltaL, adjustColorSL m.colors[3]! newHues[3]! deltaS deltaL, adjustColorSL m.colors[4]! newHues[4]! deltaS deltaL] else #[adjustColorSL m.colors[0]! (normalizeHue ((m.colors[0]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[1]! (normalizeHue ((m.colors[1]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[2]! (normalizeHue ((m.colors[2]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[3]! (normalizeHue ((m.colors[3]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[4]! (normalizeHue ((m.colors[4]!).h + deltaH)) deltaS deltaL]
  let moodBroken := m.mood ≠ .Custom ∧ ¬(allColorsSatisfyMood adjustedColors m.mood)
  let newMood := if moodBroken then .Custom else m.mood
  { m with baseHue := newBaseHue, colors := adjustedColors, mood := newMood }

def applySetColorDirect (m : Model) (index : Int) (color : Color) : Model :=
  let clampedColor := clampColor color
  let expectedHues := allHarmonyHues m.baseHue m.harmony
  let hueMatches := expectedHues.size = 5 ∧ clampedColor.h = expectedHues[index.toNat]!
  let harmonyPreserved := m.harmony = .Custom ∨ hueMatches
  let moodPreserved := m.mood = .Custom ∨ colorSatisfiesMood clampedColor m.mood
  let newColors := m.colors.set! index.toNat clampedColor
  let newHarmony := if harmonyPreserved then m.harmony else .Custom
  let newMood := if moodPreserved then m.mood else .Custom
  { m with colors := newColors, harmony := newHarmony, mood := newMood }

def normalizeModel (m : Model) : Model :=
  let normalizedBaseHue := normalizeHue m.baseHue
  let normalizedColors := if (m.colors).size = 5 then #[clampColor m.colors[0]!, clampColor m.colors[1]!, clampColor m.colors[2]!, clampColor m.colors[3]!, clampColor m.colors[4]!] else #[{ h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }]
  let normalizedContrastPair := if 0 ≤ (m.contrastPair).fg ∧ (m.contrastPair).fg < 5 ∧ 0 ≤ (m.contrastPair).bg ∧ (m.contrastPair).bg < 5 then m.contrastPair else { fg := 0, bg := 1 }
  let finalMood := if m.mood = .Custom then .Custom else if allColorsSatisfyMood normalizedColors m.mood then m.mood else .Custom
  let finalHarmony := if m.harmony = .Custom then .Custom else if huesMatchHarmony normalizedColors normalizedBaseHue m.harmony then m.harmony else .Custom
  { m with baseHue := normalizedBaseHue, colors := normalizedColors, contrastPair := normalizedContrastPair, mood := finalMood, harmony := finalHarmony }

def validBaseHue (h : Int) : Bool :=
  h ≥ 0 ∧ h < 360

def validRandomSeeds (seeds : Array Int) : Bool :=
  seeds[0]! ≥ 0 ∧ seeds[0]! ≤ 100 ∧ seeds[1]! ≥ 0 ∧ seeds[1]! ≤ 100 ∧ seeds[2]! ≥ 0 ∧ seeds[2]! ≤ 100 ∧ seeds[3]! ≥ 0 ∧ seeds[3]! ≤ 100 ∧ seeds[4]! ≥ 0 ∧ seeds[4]! ≤ 100 ∧ seeds[5]! ≥ 0 ∧ seeds[5]! ≤ 100 ∧ seeds[6]! ≥ 0 ∧ seeds[6]! ≤ 100 ∧ seeds[7]! ≥ 0 ∧ seeds[7]! ≤ 100 ∧ seeds[8]! ≥ 0 ∧ seeds[8]! ≤ 100 ∧ seeds[9]! ≥ 0 ∧ seeds[9]! ≤ 100

def applySelectContrastPair (m : Model) (fg : Int) (bg : Int) : Model :=
  if 0 ≤ fg ∧ fg < 5 ∧ 0 ≤ bg ∧ bg < 5 then
    { m with contrastPair := { fg := fg, bg := bg } }
  else
    m

def applyGeneratePalette (m : Model) (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Model :=
  if ¬(validBaseHue baseHue) ∨ randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors baseHue mood harmony randomSeeds
    { m with baseHue := baseHue, mood := mood, harmony := harmony, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyAdjustPalette (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let adjusted := applyLinkedAdjustment m deltaH deltaS deltaL
  { adjusted with adjustmentH := m.adjustmentH + deltaH, adjustmentS := m.adjustmentS + deltaS, adjustmentL := m.adjustmentL + deltaL }

def applyRegenerateMood (m : Model) (mood : Mood) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors m.baseHue mood m.harmony randomSeeds
    { m with mood := mood, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyRegenerateHarmony (m : Model) (harmony : Harmony) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors m.baseHue m.mood harmony randomSeeds
    { m with harmony := harmony, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyRandomizeBaseHue (m : Model) (newBaseHue : Int) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) ∨ ¬(validBaseHue newBaseHue) then
    m
  else
    let colors := generatePaletteColors newBaseHue m.mood m.harmony randomSeeds
    { m with baseHue := newBaseHue, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def validAction (a : Action) : Bool :=
  match a with
  | .AdjustColor _a_index _a_deltaH _a_deltaS _a_deltaL =>
    _a_index ≥ 0 ∧ _a_index < 5
  | .SetColorDirect _a_index _a_color =>
    _a_index ≥ 0 ∧ _a_index < 5
  | _ =>
    true

def apply (m : Model) (a : Action) : Model :=
  match a with
  | .GeneratePalette _a_baseHue _a_mood _a_harmony _a_randomSeeds =>
    applyGeneratePalette m _a_baseHue _a_mood _a_harmony _a_randomSeeds
  | .AdjustColor _a_index _a_deltaH _a_deltaS _a_deltaL =>
    applyIndependentAdjustment m _a_index _a_deltaH _a_deltaS _a_deltaL
  | .AdjustPalette _a_deltaH _a_deltaS _a_deltaL =>
    applyAdjustPalette m _a_deltaH _a_deltaS _a_deltaL
  | .SelectContrastPair _a_fg _a_bg =>
    applySelectContrastPair m _a_fg _a_bg
  | .SetColorDirect _a_index _a_color =>
    applySetColorDirect m _a_index _a_color
  | .RegenerateMood _a_mood _a_randomSeeds =>
    applyRegenerateMood m _a_mood _a_randomSeeds
  | .RegenerateHarmony _a_harmony _a_randomSeeds =>
    applyRegenerateHarmony m _a_harmony _a_randomSeeds
  | .RandomizeBaseHue _a_newBaseHue _a_randomSeeds =>
    applyRandomizeBaseHue m _a_newBaseHue _a_randomSeeds

def step (m : Model) (a : Action) : Model :=
  normalizeModel (apply m a)

def init  : Model :=
  let randomSeeds := #[50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  let baseHue := 180
  let mood := .Vibrant
  let harmony := .Complementary
  let colors := generatePaletteColors baseHue mood harmony randomSeeds
  { baseHue := baseHue, mood := mood, harmony := harmony, colors := colors, contrastPair := { fg := 0, bg := 1 }, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

end Pure
