/-
  Generated by lsc from colorwheel.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «colorwheel.spec»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method clamp (x : Int) (min : Int) (max : Int) return (res : Int)
  require min ≤ max
  ensures res ≥ min
  ensures res ≤ max
  do
    return Pure.clamp x min max

method normalizeHue (h : Int) return (res : Int)
  ensures res ≥ 0
  ensures res < 360
  do
    return Pure.normalizeHue h

method clampColor (c : Color) return (res : Color)
  ensures res.h ≥ 0
  ensures res.h < 360
  ensures res.s ≥ 0
  ensures res.s ≤ 100
  ensures res.l ≥ 0
  ensures res.l ≤ 100
  do
    return Pure.clampColor c

method moodBoundsOf (mood : Mood) return (res : MoodBoundsResult)
  do
    return Pure.moodBoundsOf mood

method colorSatisfiesMood (c : Color) (mood : Mood) return (res : Bool)
  do
    return Pure.colorSatisfiesMood c mood

method randomInRange (seed : Int) (min : Int) (max : Int) return (res : Int)
  require seed ≥ 0
  require seed ≤ 100
  require min ≤ max
  ensures res ≥ min
  ensures res ≤ max
  do
    return Pure.randomInRange seed min max

method goldenSLForMood (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) return (res : SLPair)
  require colorIndex ≥ 0
  require colorIndex < 5
  require seedS ≥ 0
  require seedS ≤ 100
  require seedL ≥ 0
  require seedL ≤ 100
  do
    return Pure.goldenSLForMood mood colorIndex seedS seedL

method generateColorGolden (h : Int) (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) return (res : Color)
  require h ≥ 0
  require h < 360
  require colorIndex ≥ 0
  require colorIndex < 5
  require seedS ≥ 0
  require seedS ≤ 100
  require seedL ≥ 0
  require seedL ≤ 100
  do
    return Pure.generateColorGolden h mood colorIndex seedS seedL

method allColorsSatisfyMood (colors : Array Color) (mood : Mood) return (res : Bool)
  require colors.size = 5
  do
    return Pure.allColorsSatisfyMood colors mood

method baseHarmonyHues (baseHue : Int) (harmony : Harmony) return (res : Array Int)
  do
    return Pure.baseHarmonyHues baseHue harmony

method allHarmonyHues (baseHue : Int) (harmony : Harmony) return (res : Array Int)
  do
    return Pure.allHarmonyHues baseHue harmony

method huesMatchHarmony (colors : Array Color) (baseHue : Int) (harmony : Harmony) return (res : Bool)
  do
    return Pure.huesMatchHarmony colors baseHue harmony

method generatePaletteColors (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) return (res : Array Color)
  require baseHue ≥ 0
  require baseHue < 360
  require randomSeeds.size = 10
  do
    return Pure.generatePaletteColors baseHue mood harmony randomSeeds

method adjustColorSL (c : Color) (newHue : Int) (deltaS : Int) (deltaL : Int) return (res : Color)
  require newHue ≥ 0
  require newHue < 360
  do
    return Pure.adjustColorSL c newHue deltaS deltaL

method applyIndependentAdjustment (m : Model) (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) return (res : Model)
  require index ≥ 0
  require index < 5
  require (m.colors).size = 5
  do
    return Pure.applyIndependentAdjustment m index deltaH deltaS deltaL

method applyLinkedAdjustment (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyLinkedAdjustment m deltaH deltaS deltaL

method applySetColorDirect (m : Model) (index : Int) (color : Color) return (res : Model)
  require index ≥ 0
  require index < 5
  require (m.colors).size = 5
  do
    return Pure.applySetColorDirect m index color

method normalizeModel (m : Model) return (res : Model)
  do
    return Pure.normalizeModel m

method validBaseHue (h : Int) return (res : Bool)
  do
    return Pure.validBaseHue h

method validRandomSeeds (seeds : Array Int) return (res : Bool)
  require seeds.size = 10
  do
    return Pure.validRandomSeeds seeds

method applySelectContrastPair (m : Model) (fg : Int) (bg : Int) return (res : Model)
  do
    return Pure.applySelectContrastPair m fg bg

method applyGeneratePalette (m : Model) (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyGeneratePalette m baseHue mood harmony randomSeeds

method applyAdjustPalette (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyAdjustPalette m deltaH deltaS deltaL

method applyRegenerateMood (m : Model) (mood : Mood) (randomSeeds : Array Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyRegenerateMood m mood randomSeeds

method applyRegenerateHarmony (m : Model) (harmony : Harmony) (randomSeeds : Array Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyRegenerateHarmony m harmony randomSeeds

method applyRandomizeBaseHue (m : Model) (newBaseHue : Int) (randomSeeds : Array Int) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.applyRandomizeBaseHue m newBaseHue randomSeeds

method apply (m : Model) (a : Action) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.apply m a

method step (m : Model) (a : Action) return (res : Model)
  require (m.colors).size = 5
  do
    return Pure.step m a

method init  return (res : Model)
  do
    return Pure.init 
